// packages/vue-ui/src/components/Table.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cn } from '../lib/cn';

interface Props {
  className?: string;
  /** Additive override for the scroll wrapper `<div>` around `<table>` (not the table itself — use `className` for that). */
  wrapperClassName?: string;
}

const props = defineProps<Props>();
const classes = computed(() => cn('w-full caption-bottom text-sm', props.className));
const wrapperClasses = computed(() =>
  cn('relative w-full overflow-x-auto', props.wrapperClassName),
);
</script>

<template>
  <div :class="wrapperClasses">
    <table data-slot="table" :class="classes"><slot /></table>
  </div>
</template>

// packages/react-ui/src/components/Table.tsx
import type { ComponentProps } from 'react';
import { cn } from '../lib/cn';

export interface TableProps extends ComponentProps<'table'> {
  /** Additive override for the scroll wrapper `<div>` around `<table>` (not the table itself — use `className` for that). */
  wrapperClassName?: string;
}

export function Table({ className, wrapperClassName, ...props }: TableProps) {
  return (
    <div className={cn('relative w-full overflow-x-auto', wrapperClassName)}>
      <table
        data-slot="table"
        className={cn('w-full caption-bottom text-sm', className)}
        {...props}
      />
    </div>
  );
}

export function TableHeader({ className, ...props }: ComponentProps<'thead'>) {
  return (
    <thead
      data-slot="table-header"
      className={cn('[&_tr]:border-b', className)}
      {...props}
    />
  );
}

export function TableBody({ className, ...props }: ComponentProps<'tbody'>) {
  return (
    <tbody
      data-slot="table-body"
      className={cn('[&_tr:last-child]:border-0', className)}
      {...props}
    />
  );
}

export function TableRow({ className, ...props }: ComponentProps<'tr'>) {
  return (
    <tr
      data-slot="table-row"
      className={cn(
        'border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted',
        className,
      )}
      {...props}
    />
  );
}

export function TableHead({ className, ...props }: ComponentProps<'th'>) {
  return (
    <th
      data-slot="table-head"
      className={cn(
        'h-12 whitespace-nowrap px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0',
        className,
      )}
      {...props}
    />
  );
}

export function TableCell({ className, ...props }: ComponentProps<'td'>) {
  return (
    <td
      data-slot="table-cell"
      className={cn('px-4 py-3 align-middle [&:has([role=checkbox])]:pr-0', className)}
      {...props}
    />
  );
}
