// react/src/FlexTable.tsx
import { useMemo } from 'react';
import { useFlexTable } from './hooks/useFlexTable';
import { useTableClientPagination } from './hooks/useTableClientPagination';
import { useColumnPinning } from './hooks/useColumnPinning';
import TableToolbar from './components/TableToolbar';
import TableContent from './components/TableContent';
import TablePagination from './components/TablePagination';
import type { SlotProps as ToolbarSlotProps } from './components/TableToolbar';
import type { SlotProps as TableContentSlotProps } from './components/TableContent';
import type { ElementType } from 'react';
import type { PaginatedResponse } from '../interfaces/pagination';
import type {
  ColumnDef,
  ColumnFilter,
  ColumnPinningPosition,
  SortingState,
  Table,
} from '@tanstack/react-table';
import { useDeviceType } from '@/hooks/useDeviceType';

interface Props<TData extends Record<string, unknown>, TValue> {
  columns: Array<ColumnDef<TData, TValue>>;
  data: Array<TData>;
  noResultsTextKey?: string;
  ofTextKey?: string;
  pinnedColumnId?: string;
  pinOnMobile?: ColumnPinningPosition;
  pinOnDesktop?: ColumnPinningPosition;
  serverSideSorting?: boolean;
  serverSideFiltering?: boolean;
  serverSidePagination?: Pick<
    PaginatedResponse<TData>,
    'itemCount' | 'page' | 'pageSize' | 'pageCount'
  >;
  useFuzzySearch?: boolean;
  searchColumns?: Array<string>;
  emit: Emits;
  assets?: ElementType<SlotProps<TData>>;
  tableFilters?: ElementType<ToolbarSlotProps<TData>>;
  tableContentComponent?: ElementType<TableContentSlotProps<TData>>;
}

interface SlotProps<TData extends Record<string, unknown>> {
  table: Table<TData>;
}

export interface Emits {
  (e: 'update:sorting', sorting: SortingState): void;
  (e: 'update:filters', filters: Array<ColumnFilter>): void;
  (e: 'update:page' | 'update:pageSize', value: number): void;
}

export default function FlexTable<
  TData extends Record<string, unknown>,
  TValue,
>(props: Props<TData, TValue>) {
  const {
    data,
    columns,
    ofTextKey = 'common.table.of',
    noResultsTextKey = 'common.noResult',
    pinnedColumnId = 'actions',
    pinOnMobile = 'right',
    pinOnDesktop = false,
    serverSideSorting = false,
    serverSideFiltering = true,
    serverSidePagination = undefined,
    useFuzzySearch = true,
    searchColumns = [],
    emit,
  } = props;
  const { isMobile } = useDeviceType();

  const { table, handleFiltersUpdate } = useFlexTable(
    {
      columns: columns,
      data: useMemo(() => data, [data]),
      serverSideSorting: serverSideSorting,
      serverSideFiltering: serverSideFiltering,
      serverSidePagination: useMemo(
        () => serverSidePagination,
        [serverSidePagination],
      ),
      useFuzzySearch: useFuzzySearch,
      searchColumns: searchColumns,
    },
    emit,
  );

  const {
    currentPagination,
    canPreviousPage,
    canNextPage,
    updatePageSize,
    goToPage,
  } = useTableClientPagination(
    {
      table,
      serverSidePagination: useMemo(
        () => serverSidePagination,
        [serverSidePagination],
      ),
    },
    emit,
  );

  const { getPinnedItemClassDefinition } = useColumnPinning({
    table,
    pinnedColumnId: pinnedColumnId,
    pinOnMobile: pinOnMobile,
    pinOnDesktop: pinOnDesktop,
    isMobile,
  });

  return (
    <div className="container mx-auto">
      <div className="mx-auto my-6 flex justify-between">
        {props.assets && <props.assets table={table} />}
      </div>
      <div className="mx-auto rounded-lg border">
        <TableToolbar
          table={table}
          handleFiltersUpdate={handleFiltersUpdate}
          tableFilters={props.tableFilters}
        />

        <TableContent
          table={table}
          columns={columns}
          noResultsTextKey={noResultsTextKey}
          getPinnedItemClassDefinition={getPinnedItemClassDefinition}
          slotComponent={props.tableContentComponent}
        />

        <TablePagination
          currentPagination={currentPagination}
          canPreviousPage={canPreviousPage}
          canNextPage={canNextPage}
          ofTextKey={ofTextKey}
          updatePageSize={updatePageSize}
          goToPage={goToPage}
        />
      </div>
    </div>
  );
}

// vue/src/FlexTable.vue
<script setup lang="ts" generic="TData extends Record<string, unknown>, TValue">
import type {
  ColumnDef,
  ColumnFilter,
  ColumnPinningPosition,
  SortingState
} from '@tanstack/vue-table'
import TableContent from '~/components/datatable/TableContent.vue'
import TablePagination from '~/components/datatable/TablePagination.vue'
import TableToolbar from '~/components/datatable/TableToolbar.vue'
import { useColumnPinning } from '~/composables/datatable/useColumnPinning'
import { useFlexTable } from '~/composables/datatable/useFlexTable'
import { useTableClientPagination } from '~/composables/datatable/useTableClientPagination'
import { useDeviceType } from '~/composables/useDeviceType'
import type { PaginatedResponse } from '~/types/pagination'

const { isMobile } = useDeviceType()

const props = withDefaults(
  defineProps<{
    columns: ColumnDef<TData, TValue>[]
    data: TData[]
    noResultsTextKey?: string
    ofTextKey?: string
    pinnedColumnId?: string
    pinOnMobile?: ColumnPinningPosition
    pinOnDesktop?: ColumnPinningPosition
    serverSideSorting?: boolean
    serverSideFiltering?: boolean
    serverSidePagination?: Pick<
      PaginatedResponse<TData>,
      'itemCount' | 'page' | 'pageSize' | 'pageCount'
    >
    useFuzzySearch?: boolean
    searchColumns?: string[]
    showSearch?: boolean
  }>(),
  {
    ofTextKey: 'common.table.of',
    noResultsTextKey: 'common.noResult',
    pinnedColumnId: 'actions',
    pinOnMobile: 'right',
    pinOnDesktop: false,
    serverSideSorting: false,
    serverSideFiltering: true,
    serverSidePagination: undefined,
    useFuzzySearch: true,
    searchColumns: () => [],
    showSearch: true
  }
)

const emit = defineEmits<{
  (e: 'update:sorting', sorting: SortingState): void
  (e: 'update:filters', filters: ColumnFilter[]): void
  (e: 'update:page' | 'update:pageSize', value: number): void
  (e: 'rowClick', row: TData): void
}>()

// Use composables
const { table, handleFiltersUpdate } = useFlexTable(
  {
    columns: props.columns,
    data: computed(() => props.data),
    serverSideSorting: props.serverSideSorting,
    serverSideFiltering: props.serverSideFiltering,
    serverSidePagination: computed(() => props.serverSidePagination),
    useFuzzySearch: props.useFuzzySearch,
    searchColumns: props.searchColumns
  },
  emit
)

const { currentPagination, canPreviousPage, canNextPage, updatePageSize, goToPage } =
  useTableClientPagination(
    { table, serverSidePagination: computed(() => props.serverSidePagination) },
    emit
  )

const { getPinnedItemClassDefinition } = useColumnPinning({
  table,
  pinnedColumnId: props.pinnedColumnId,
  pinOnMobile: props.pinOnMobile,
  pinOnDesktop: props.pinOnDesktop,
  isMobile
})

defineExpose({
  table: () => table
})
</script>

<template>
  <div>
    <div class="mx-auto my-6 flex justify-between">
      <slot
        name="asset"
        :table="table"
      />
    </div>
    <div class="mx-auto rounded-lg border">
      <TableToolbar
        :table="table"
        :handle-filters-update="handleFiltersUpdate"
        :show-search="props.showSearch"
      >
        <template
          #tableFilters="{ table: slotTable, handleFiltersUpdate: slotHandleFiltersUpdate }"
        >
          <slot
            name="tableFilters"
            :table="slotTable"
            :handle-filters-update="slotHandleFiltersUpdate"
          />
        </template>
      </TableToolbar>

      <TableContent
        :table="table"
        :columns="columns"
        :no-results-text-key="props.noResultsTextKey"
        :get-pinned-item-class-definition="getPinnedItemClassDefinition"
        @row-click="(row: TData) => emit('rowClick', row)"
      >
        <template #expandedRowContent="{ row, table: slotTable }">
          <slot
            name="expandedRowContent"
            :row="row"
            :table="slotTable"
          />
        </template>
      </TableContent>

      <TablePagination
        :current-pagination="currentPagination"
        :can-previous-page="canPreviousPage"
        :can-next-page="canNextPage"
        :of-text-key="props.ofTextKey"
        :update-page-size="updatePageSize"
        :go-to-page="goToPage"
      />
    </div>
  </div>
</template>
