// packages/vue-ui/src/entity/EntityTitle.vue
<script setup lang="ts">
import { computed } from 'vue';
import { cn } from '../lib/cn';

interface Props {
  title: string;
  description?: string;
  titleClassName?: string;
  descriptionClassName?: string;
  hasDescription?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  description: '',
  titleClassName: '',
  descriptionClassName: '',
  hasDescription: true,
});

const titleClasses = computed(() =>
  cn(
    'truncate text-foreground',
    props.titleClassName,
    props.hasDescription && 'font-medium',
  ),
);
const descriptionClasses = computed(() =>
  cn('w-full truncate text-muted-foreground', props.descriptionClassName),
);
</script>

<template>
  <div class="flex w-full flex-col">
    <span :class="titleClasses" data-testid="entity-title">{{ title }}</span>
    <span v-if="hasDescription && description" :class="descriptionClasses" data-testid="entity-description">
      {{ description }}
    </span>
  </div>
</template>

// packages/react-ui/src/entity/EntityTitle.tsx
import { cn } from '../lib/cn';

export interface EntityTitleProps {
  title: string;
  description?: string;
  titleClassName?: string;
  descriptionClassName?: string;
  hasDescription?: boolean;
}

/** Direct port of obaas-frontend's shared/entity/TitleWithDesc.tsx — zero app coupling to begin with. */
export function EntityTitle({
  title,
  description = '',
  titleClassName = '',
  descriptionClassName = '',
  hasDescription = true,
}: EntityTitleProps) {
  return (
    <div className="flex w-full flex-col">
      <span
        className={cn(
          'truncate text-foreground',
          titleClassName,
          hasDescription && 'font-medium',
        )}
        data-testid="entity-title"
      >
        {title}
      </span>
      {hasDescription && description && (
        <span
          className={cn('w-full truncate text-muted-foreground', descriptionClassName)}
          data-testid="entity-description"
        >
          {description}
        </span>
      )}
    </div>
  );
}
