// packages/react/src/FlexTable.tsx
import type {
  FlexTableClassNames,
  FlexTableKeys,
  PaginatedResponse,
  TranslateFn,
} from '@flextable/core';
import { resolveFlexTableKeys } from '@flextable/core';
import { cn } from '@flextable/react-ui';
import type {
  ColumnDef,
  ColumnFilter,
  ColumnPinningPosition,
  SortingState,
  Table,
} from '@tanstack/react-table';
import type { ElementType } from 'react';
import { useCallback, useMemo } from 'react';
import type { SlotProps as TableContentSlotProps } from './components/TableContent';
import { TableContent } from './components/TableContent';
import { TablePagination } from './components/TablePagination';
import type { ToolbarSlotProps } from './components/TableToolbar';
import { TableToolbar } from './components/TableToolbar';
import { TablePaginationProvider } from './helpers/TablePaginationProvider';
import { useColumnPinning } from './hooks/useColumnPinning';
import { useDeviceType } from './hooks/useDeviceType';
import { useFlexTable } from './hooks/useFlexTable';
import { useTableClientPagination } from './hooks/useTableClientPagination';

export interface FlexTableSlotProps<TData> {
  table: Table<TData>;
  /** Calls `table.setGlobalFilter()` under the hood — the discoverable way for a custom `assets` component to drive the same search state as the built-in search box (and, in turn, `onSearchChange`). */
  handleSearchUpdate: (value: string) => void;
}

export interface FlexTableProps<TData, TValue> {
  columns: Array<ColumnDef<TData, TValue>>;
  data: Array<TData>;
  t: TranslateFn;
  /** Overrides for the fixed translation keys used by the table's built-in chrome — see `FlexTableKeys`. */
  keys?: Partial<FlexTableKeys>;
  /** Additive className overrides for FlexTable's own structural layers — see `FlexTableClassNames`. */
  classNames?: FlexTableClassNames;
  pinnedColumnId?: string;
  pinOnMobile?: ColumnPinningPosition;
  pinOnDesktop?: ColumnPinningPosition;
  serverSideSorting?: boolean;
  serverSideFiltering?: boolean;
  serverSidePagination?: Pick<
    PaginatedResponse<TData>,
    'itemCount' | 'page' | 'pageSize' | 'pageCount'
  >;
  useFuzzySearch?: boolean;
  searchColumns?: Array<string>;
  onSortingChange?: (sorting: SortingState) => void;
  onFiltersChange?: (filters: Array<ColumnFilter>) => void;
  /** Fires on every search-input change, regardless of `serverSideFiltering` — the dedicated hook for driving a server-side search independently of the rest of the table's filtering mode. */
  onSearchChange?: (value: string) => void;
  onPageChange?: (page: number) => void;
  onPageSizeChange?: (pageSize: number) => void;
  assets?: ElementType<FlexTableSlotProps<TData>>;
  tableFilters?: ElementType<ToolbarSlotProps<TData>>;
  tableContentComponent?: ElementType<TableContentSlotProps<TData>>;
}

function FlexTableInner<TData, TValue>(props: FlexTableProps<TData, TValue>) {
  const {
    data,
    columns,
    t,
    keys: keysOverride,
    classNames = {},
    pinnedColumnId = 'actions',
    pinOnMobile = 'right',
    pinOnDesktop = false,
    serverSideSorting = false,
    serverSideFiltering = true,
    serverSidePagination,
    useFuzzySearch = true,
    searchColumns = [],
    onSortingChange,
    onFiltersChange,
    onSearchChange,
    onPageChange,
    onPageSizeChange,
  } = props;
  const keys = useMemo(() => resolveFlexTableKeys(keysOverride), [keysOverride]);
  const { isMobile } = useDeviceType();

  const { table, handleFiltersUpdate } = useFlexTable<TData, TValue>(
    {
      columns,
      data: useMemo(() => data, [data]),
      serverSideSorting,
      serverSideFiltering,
      serverSidePagination: useMemo(() => serverSidePagination, [serverSidePagination]),
      useFuzzySearch,
      searchColumns,
    },
    (event, value) => {
      if (event === 'update:sorting') onSortingChange?.(value as SortingState);
      if (event === 'update:filters') onFiltersChange?.(value as Array<ColumnFilter>);
      if (event === 'update:search') onSearchChange?.(value as string);
    },
  );

  const { currentPagination, canPreviousPage, canNextPage, updatePageSize, goToPage } =
    useTableClientPagination(
      {
        table,
        serverSidePagination: useMemo(() => serverSidePagination, [serverSidePagination]),
      },
      (event, value) => {
        if (event === 'update:page') onPageChange?.(value);
        if (event === 'update:pageSize') onPageSizeChange?.(value);
      },
    );

  const { getPinnedItemClassDefinition } = useColumnPinning({
    table,
    pinnedColumnId,
    pinOnMobile,
    pinOnDesktop,
    isMobile,
  });

  const handleSearchUpdate = useCallback(
    (value: string) => table.setGlobalFilter(value),
    [table],
  );

  return (
    <div className={cn('@container container mx-auto', classNames.container)}>
      <div className={cn('mx-auto my-6 flex justify-between', classNames.assets)}>
        {props.assets && (
          <props.assets table={table} handleSearchUpdate={handleSearchUpdate} />
        )}
      </div>
      <div className={cn('mx-auto rounded-lg border', classNames.card)}>
        <TableToolbar
          table={table}
          t={t}
          keys={keys}
          className={classNames.toolbar}
          handleFiltersUpdate={handleFiltersUpdate}
          handleSearchUpdate={handleSearchUpdate}
          tableFilters={props.tableFilters}
        />

        <TableContent
          table={table}
          columns={columns}
          t={t}
          keys={keys}
          className={classNames.content}
          getPinnedItemClassDefinition={getPinnedItemClassDefinition}
          slotComponent={props.tableContentComponent}
        />

        <TablePagination
          t={t}
          currentPagination={currentPagination}
          canPreviousPage={canPreviousPage}
          canNextPage={canNextPage}
          keys={keys}
          className={classNames.pagination}
          updatePageSize={updatePageSize}
          goToPage={goToPage}
        />
      </div>
    </div>
  );
}

export function FlexTable<TData, TValue>(props: FlexTableProps<TData, TValue>) {
  return (
    <TablePaginationProvider>
      <FlexTableInner {...props} />
    </TablePaginationProvider>
  );
}

// packages/vue/src/FlexTable.vue
<script setup lang="ts" generic="TData, TValue">
import type {
  FlexTableClassNames,
  FlexTableKeys,
  PaginatedResponse,
  TranslateFn,
} from '@flextable/core';
import { resolveFlexTableKeys } from '@flextable/core';
import { cn } from '@flextable/vue-ui';
import type {
  ColumnDef,
  ColumnFilter,
  ColumnPinningPosition,
  SortingState,
  Table,
} from '@tanstack/vue-table';
import { computed, provide } from 'vue';
import TableContent from './components/TableContent.vue';
import TablePagination from './components/TablePagination.vue';
import TableToolbar from './components/TableToolbar.vue';
import { TABLE_LOADING_STATE_KEY } from './composables/tableLoadingState';
import { useColumnPinning } from './composables/useColumnPinning';
import { useDeviceType } from './composables/useDeviceType';
import { useFlexTable } from './composables/useFlexTable';
import { useTableClientPagination } from './composables/useTableClientPagination';

const props = withDefaults(
  defineProps<{
    columns: Array<ColumnDef<TData, TValue>>;
    data: Array<TData>;
    t: TranslateFn;
    keys?: Partial<FlexTableKeys>;
    classNames?: FlexTableClassNames;
    pinnedColumnId?: string;
    pinOnMobile?: ColumnPinningPosition;
    pinOnDesktop?: ColumnPinningPosition;
    serverSideSorting?: boolean;
    serverSideFiltering?: boolean;
    serverSidePagination?: Pick<
      PaginatedResponse<TData>,
      'itemCount' | 'page' | 'pageSize' | 'pageCount'
    >;
    useFuzzySearch?: boolean;
    searchColumns?: Array<string>;
    showSearch?: boolean;
    loading?: boolean;
  }>(),
  {
    keys: undefined,
    classNames: undefined,
    pinnedColumnId: 'actions',
    pinOnMobile: 'right',
    pinOnDesktop: false,
    serverSideSorting: false,
    serverSideFiltering: true,
    serverSidePagination: undefined,
    useFuzzySearch: true,
    searchColumns: () => [],
    showSearch: true,
    loading: false,
  },
);

const emit = defineEmits<{
  (e: 'update:sorting', sorting: SortingState): void;
  (e: 'update:filters', filters: Array<ColumnFilter>): void;
  (e: 'update:search', value: string): void;
  (e: 'update:page', value: number): void;
  (e: 'update:pageSize', value: number): void;
  (e: 'rowClick', row: TData): void;
}>();

provide(
  TABLE_LOADING_STATE_KEY,
  computed(() => props.loading),
);

const resolvedKeys = computed(() => resolveFlexTableKeys(props.keys));

const containerClass = computed(() => cn('@container', props.classNames?.container));
const assetsClass = computed(() =>
  cn('mx-auto my-6 flex justify-between', props.classNames?.assets),
);
const cardClass = computed(() => cn('mx-auto rounded-lg border', props.classNames?.card));

const { isMobile } = useDeviceType();

const { table, handleFiltersUpdate } = useFlexTable<TData, TValue>(
  {
    columns: props.columns,
    data: computed(() => props.data),
    serverSideSorting: props.serverSideSorting,
    serverSideFiltering: props.serverSideFiltering,
    serverSidePagination: computed(() => props.serverSidePagination),
    useFuzzySearch: props.useFuzzySearch,
    searchColumns: props.searchColumns,
  },
  (event, value) => {
    if (event === 'update:sorting') emit('update:sorting', value as SortingState);
    else if (event === 'update:search') emit('update:search', value as string);
    else emit('update:filters', value as Array<ColumnFilter>);
  },
);

const handleSearchUpdate = (value: string) => table.setGlobalFilter(value);

const { currentPagination, canPreviousPage, canNextPage, updatePageSize, goToPage } =
  useTableClientPagination(
    { table, serverSidePagination: computed(() => props.serverSidePagination) },
    (event, value) => {
      if (event === 'update:page') emit('update:page', value as number);
      else emit('update:pageSize', value as number);
    },
  );

const { getPinnedItemClassDefinition } = useColumnPinning({
  table,
  pinnedColumnId: props.pinnedColumnId,
  pinOnMobile: props.pinOnMobile,
  pinOnDesktop: props.pinOnDesktop,
  isMobile,
});

defineSlots<{
  asset?(props: {
    table: Table<TData>;
    handleSearchUpdate: (value: string) => void;
  }): unknown;
  tableFilters?(props: {
    table: Table<TData>;
    handleFiltersUpdate: (columnFilters: Array<ColumnFilter>) => void;
    handleSearchUpdate: (value: string) => void;
  }): unknown;
  expandedRowContent?(props: { row: unknown; table: Table<TData> }): unknown;
}>();

defineExpose({ table: () => table });
</script>

<template>
  <div :class="containerClass">
    <div :class="assetsClass">
      <slot name="asset" :table="table" :handle-search-update="handleSearchUpdate" />
    </div>
    <div :class="cardClass">
      <TableToolbar
        :table="table"
        :t="t"
        :keys="resolvedKeys"
        :class-name="classNames?.toolbar"
        :handle-filters-update="handleFiltersUpdate"
        :handle-search-update="handleSearchUpdate"
        :show-search="showSearch"
      >
        <template #tableFilters="{ table: slotTable, handleFiltersUpdate: slotHandleFiltersUpdate, handleSearchUpdate: slotHandleSearchUpdate }">
          <slot
            name="tableFilters"
            :table="slotTable"
            :handle-filters-update="slotHandleFiltersUpdate"
            :handle-search-update="slotHandleSearchUpdate"
          />
        </template>
      </TableToolbar>

      <TableContent
        :table="table"
        :columns="columns"
        :t="t"
        :keys="resolvedKeys"
        :class-name="classNames?.content"
        :get-pinned-item-class-definition="getPinnedItemClassDefinition"
        @row-click="(row: TData) => emit('rowClick', row)"
      >
        <template #expandedRowContent="{ row, table: slotTable }">
          <slot name="expandedRowContent" :row="row" :table="slotTable" />
        </template>
      </TableContent>

      <TablePagination
        :t="t"
        :current-pagination="currentPagination"
        :can-previous-page="canPreviousPage"
        :can-next-page="canNextPage"
        :keys="resolvedKeys"
        :class-name="classNames?.pagination"
        :update-page-size="updatePageSize"
        :go-to-page="goToPage"
      />
    </div>
  </div>
</template>
