// packages/vue/src/components/TableDropdown.vue
<script setup lang="ts" generic="TData">
import type { FlexTableKeys, TranslateFn } from '@flextable/core';
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from '@flextable/vue-ui';
import { ChevronDown, ChevronUp } from '@lucide/vue';
import type { Column, Table } from '@tanstack/vue-table';
import { ref } from 'vue';

export interface TableDropdownProps<TData> {
  table: Table<TData>;
  t: TranslateFn;
  keys: FlexTableKeys;
}

const props = defineProps<TableDropdownProps<TData>>();
const emit = defineEmits<{ open: [value: boolean] }>();
const isOpen = ref(false);

function getDropDownItemName(column: Column<TData, unknown>): string {
  const translated = props.t(`common.${column.id}`);
  return translated !== `common.${column.id}` ? translated : column.id;
}

function onOpenChange(value: boolean) {
  isOpen.value = value;
  emit('open', value);
}
</script>

<template>
  <DropdownMenu :open="isOpen" @update:open="onOpenChange">
    <DropdownMenuTrigger as-child>
      <span
        class="ml-auto flex w-full cursor-pointer items-center justify-between gap-2 rounded-md border p-2 hover:border-ring hover:bg-transparent @lg:w-auto"
      >
        {{ t(keys.columns) }}
        <ChevronUp v-if="isOpen" class="ml-2 h-4 w-4" />
        <ChevronDown v-else class="ml-2 h-4 w-4" />
      </span>
    </DropdownMenuTrigger>
    <DropdownMenuContent align="center">
      <DropdownMenuCheckboxItem
        v-for="column in table.getAllColumns().filter((c) => c.getCanHide())"
        :key="column.id"
        class="capitalize"
        :checked="column.getIsVisible()"
        @update:checked="(value) => column.toggleVisibility(value)"
      >
        {{ getDropDownItemName(column) }}
      </DropdownMenuCheckboxItem>
    </DropdownMenuContent>
  </DropdownMenu>
</template>

// react/src/components/TableDropdown.tsx
import { ChevronDown, ChevronUp } from 'lucide-react';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import type { Column, Table } from '@tanstack/react-table';
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

interface Props<TData extends Record<string, unknown>> {
  table: Table<TData>;
  open?: (value: boolean) => void;
}

export default function TableDropdown<TData extends Record<string, unknown>>({
  table,
  open,
}: Props<TData>) {
  const [isOpen, setOpen] = useState(false);
  const { t } = useTranslation();

  function getDropDownItemName(column: Column<TData, unknown>): string {
    if (t(`common.${column.id}`) !== `common.${column.id}`) {
      return t(`common.${column.id}`);
    }
    return column.id;
  }

  return (
    <DropdownMenu
      open={isOpen}
      onOpenChange={(v) => {
        setOpen(v);
        if (open) {
          open(v);
        }
      }}
    >
      <DropdownMenuTrigger asChild>
        <span className="flex gap-2 items-center ml-auto border cursor-pointer p-2 rounded-md w-full justify-between lg:w-auto hover:border-ring focus:border:ring hover:bg-transparent">
          {t('common.columns')}
          {isOpen ? (
            <ChevronUp className="ml-2 h-4 w-4" />
          ) : (
            <ChevronDown className="ml-2 h-4 w-4" />
          )}
        </span>
      </DropdownMenuTrigger>
      <DropdownMenuContent
        align="center"
        className="w-[var(--reka-dropdown-menu-trigger-width)] md:w-full"
      >
        {table
          .getAllColumns()
          .filter((column) => column.getCanHide())
          .map((column) => (
            <DropdownMenuCheckboxItem
              key={column.id}
              className="capitalize"
              checked={column.getIsVisible()}
              onCheckedChange={(value) => column.toggleVisibility(!!value)}
            >
              {getDropDownItemName(column)}
            </DropdownMenuCheckboxItem>
          ))}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
