// vue/src/components/TableContent.vue
<script setup lang="ts" generic="TData, TValue">
import {
  TableBody,
  TableCell,
  Table as TableComponent,
  TableHead,
  TableHeader,
  TableRow
} from '@/components/ui/table'
import type { ColumnDef, ColumnPinningPosition, Row, Table } from '@tanstack/vue-table'
import { FlexRender } from '@tanstack/vue-table'
import { cn } from '~/utils'

interface Props {
  table: Table<TData>
  columns: ColumnDef<TData, TValue>[]
  noResultsTextKey: string
  getPinnedItemClassDefinition: (
    index: number,
    itemsLength: number,
    pinnedState: ColumnPinningPosition
  ) => Record<string, boolean>
}

defineProps<Props>()

const emit = defineEmits<{
  (e: 'rowClick', row: TData): void
}>()

function handleRowClick(row: Row<TData>, event: MouseEvent) {
  const target = event.target as HTMLElement

  // Check if the click is within a table cell
  const tableCell = target.closest('td')
  if (!tableCell) {
    return
  }

  // Get the cell index to determine which column was clicked
  const cells = row.getVisibleCells()
  const cellIndex = Array.from(tableCell.parentElement?.children || []).indexOf(tableCell)
  const clickedCell = cells[cellIndex]

  // Don't trigger row click for select or actions columns
  if (clickedCell?.column.id === 'select' || clickedCell?.column.id === 'actions') {
    return
  }

  emit('rowClick', row.original)
}

defineSlots<{
  expandedRowContent(props: { row: Row<TData>; table: Table<TData> }): unknown
}>()
</script>

<template>
  <div>
    <TableComponent>
      <TableHeader class="h-13 border-b-2">
        <TableRow
          v-for="headerGroup in table.getHeaderGroups()"
          :key="headerGroup.id"
        >
          <TableHead
            v-for="(header, index) in headerGroup.headers"
            :key="header.id"
            :class="
              cn(
                getPinnedItemClassDefinition(
                  index,
                  headerGroup.headers.length,
                  header.column.getIsPinned()
                )
              )
            "
          >
            <FlexRender
              v-if="!header.isPlaceholder"
              :render="header.column.columnDef.header"
              :props="header.getContext()"
            />
          </TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <template v-if="table.getRowModel().rows.length">
          <template
            v-for="row in table.getRowModel().rows"
            :key="row.id"
          >
            <TableRow
              class="px-4"
              :data-state="row.getIsSelected() && 'selected'"
              @click="(event: MouseEvent) => handleRowClick(row, event)"
            >
              <TableCell
                v-for="(cell, index) in row.getVisibleCells()"
                :key="cell.id"
                :class="
                  cn(
                    getPinnedItemClassDefinition(
                      index,
                      row.getVisibleCells().length,
                      cell.column.getIsPinned()
                    )
                  )
                "
              >
                <FlexRender
                  :render="cell.column.columnDef.cell"
                  :props="cell.getContext()"
                />
              </TableCell>
            </TableRow>
            <TableRow
              v-if="row.getIsExpanded()"
              :data-state="'expanded'"
            >
              <TableCell :colspan="row.getAllCells().length">
                <slot
                  name="expandedRowContent"
                  :row="row"
                  :table="table"
                >
                  <pre class="bg-muted rounded p-2 text-xs">{{
                    JSON.stringify(row.original, null, 2)
                  }}</pre>
                </slot>
              </TableCell>
            </TableRow>
          </template>
        </template>

        <TableRow v-else>
          <TableCell
            :colspan="columns.length"
            class="h-24 text-center"
          >
            {{ $t(noResultsTextKey || 'common.noResult') }}
          </TableCell>
        </TableRow>
      </TableBody>
    </TableComponent>
  </div>
</template>

// react/src/components/TableContent.tsx
import { flexRender } from '@tanstack/react-table';
import { useTranslation } from 'react-i18next';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../../../components/ui/table';
import type {
  ColumnDef,
  ColumnPinningPosition,
  Row,
  Table as TableType,
} from '@tanstack/react-table';
import type { ElementType } from 'react';
import { cn } from '@/lib/utils';

interface Props<TData extends Record<string, unknown>, TValue> {
  table: TableType<TData>;
  columns: Array<ColumnDef<TData, TValue>>;
  noResultsTextKey: string;
  getPinnedItemClassDefinition: (
    index: number,
    itemsLength: number,
    pinnedState: ColumnPinningPosition,
  ) => Record<string, boolean>;
  slotComponent?: ElementType<SlotProps<TData>>;
}

export interface SlotProps<TData extends Record<string, unknown>> {
  row: Row<TData>;
  table: TableType<TData>;
}

export default function TableContent<
  TData extends Record<string, unknown>,
  TValue,
>(config: Props<TData, TValue>) {
  const {
    table,
    columns,
    noResultsTextKey,
    getPinnedItemClassDefinition,
    slotComponent,
  } = config;
  const { t } = useTranslation();
  return (
    <div>
      <Table>
        <TableHeader className="h-13 border-b-2">
          {table.getHeaderGroups().map((group) => (
            <TableRow key={group.id}>
              {group.headers.map((header, index) => (
                <TableHead
                  key={header.id}
                  className={cn(
                    getPinnedItemClassDefinition(
                      index,
                      group.headers.length,
                      header.column.getIsPinned(),
                    ),
                  )}
                >
                  {flexRender(
                    header.column.columnDef.header,
                    header.getContext(),
                  )}
                </TableHead>
              ))}
            </TableRow>
          ))}
        </TableHeader>

        <TableBody>
          {table.getRowModel().rows.length ? (
            table
              .getRowModel()
              .rows.map((row) => (
                <RowChild
                  key={row.id}
                  row={row}
                  table={table}
                  getPinnedItemClassDefinition={getPinnedItemClassDefinition}
                  slotComponent={slotComponent}
                />
              ))
          ) : (
            <TableRow>
              <TableCell colSpan={columns.length} className="h-24 text-center">
                {t(noResultsTextKey || 'common.noResult')}
              </TableCell>
            </TableRow>
          )}
        </TableBody>
      </Table>
    </div>
  );
}

function DefaultSlot<TData extends Record<string, unknown>>({
  row,
}: SlotProps<TData>) {
  return (
    <pre className="bg-muted rounded p-2 text-xs">
      {JSON.stringify(row.original, null, 2)}
    </pre>
  );
}

function RowChild<TData extends Record<string, unknown>>(config: {
  table: TableType<TData>;
  row: Row<TData>;
  slotComponent?: ElementType<SlotProps<TData>>;
  getPinnedItemClassDefinition: (
    index: number,
    itemsLength: number,
    pinnedState: ColumnPinningPosition,
  ) => Record<string, boolean>;
}) {
  const { row, table, getPinnedItemClassDefinition } = config;
  return (
    <>
      <TableRow
        key={row.id}
        className="px-4"
        aria-selected={row.getIsSelected()}
      >
        {row.getVisibleCells().map((cell, index) => (
          <TableCell
            key={cell.id}
            className={cn(
              getPinnedItemClassDefinition(
                index,
                row.getVisibleCells().length,
                cell.column.getIsPinned(),
              ),
            )}
          >
            {flexRender(cell.column.columnDef.cell, cell.getContext())}
          </TableCell>
        ))}
      </TableRow>
      {row.getIsExpanded() && (
        <TableRow aria-expanded key={row.id}>
          <TableCell colSpan={row.getAllCells().length}>
            {config.slotComponent ? (
              <config.slotComponent row={row} table={table} />
            ) : (
              <DefaultSlot row={row} table={table} />
            )}
          </TableCell>
        </TableRow>
      )}
    </>
  );
}
