// vue/src/components/TableToolbar.vue
<script setup lang="ts" generic="TData extends Record<string, unknown>">
import type { ColumnFilter, Table } from '@tanstack/vue-table'
import { computed, useSlots, type VNode } from 'vue' // Import VNode for type safety
import TableDropdown from '~/components/forms/TableDropdown.vue'
import { isVNodeEmpty } from '~/utils/helpers/vnodes'
import TableSearchWithButton from '../forms/TableSearchWithButton.vue'

interface Props {
  table: Table<TData>
  handleFiltersUpdate: (columnFilters: ColumnFilter[], table: Table<TData>) => void
  showSearch?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  showSearch: true
})

const slots = useSlots()

const hasTableFiltersSlotContent = computed(() => {
  if (slots.tableFilters) {
    const slotProps = {
      table: props.table,
      handleFiltersUpdate: (columnFilters: ColumnFilter[]) =>
        props.handleFiltersUpdate(columnFilters, props.table)
    }
    const vnodes: VNode[] = slots.tableFilters(slotProps) ?? []

    if (vnodes.length === 0) {
      return false
    }

    return !vnodes.every((v) => isVNodeEmpty(v, false))
  }
  return false
})

defineSlots<{
  tableFilters(props: {
    table: Table<TData>
    handleFiltersUpdate: (columnFilters: ColumnFilter[]) => void
  }): unknown
}>()
</script>

<template>
  <div class="border-b-2 px-4 py-3">
    <div class="flex flex-col items-center gap-2 lg:flex-row">
      <div class="flex w-full flex-col items-center gap-3 lg:w-[80%] lg:flex-row">
        <TableSearchWithButton
          v-if="props.showSearch"
          data-testid="search-bar"
          :class-name="hasTableFiltersSlotContent ? 'lg:max-w-[35%]' : 'lg:max-w-[65%]'"
          @update="(value: string) => table.setGlobalFilter(value)"
        />
        <slot
          name="tableFilters"
          :table="table"
          :handle-filters-update="
            (columnFilters: ColumnFilter[]) => handleFiltersUpdate(columnFilters, table)
          "
        />
      </div>
      <TableDropdown :table="table" />
    </div>
  </div>
</template>

// react/src/components/TableToolbar.tsx
import TableSearchWithButton from './TableSearchWithButton';
import TableDropdown from './TableDropdown';
import type { ColumnFilter, Table } from '@tanstack/react-table';
import type { ElementType } from 'react';

interface Props<TData extends Record<string, unknown>> {
  table: Table<TData>;
  handleFiltersUpdate: (
    columnFilters: Array<ColumnFilter>,
    table: Table<TData>,
  ) => void;
  tableFilters?: ElementType<SlotProps<TData>>;
}

export interface SlotProps<TData extends Record<string, unknown>> {
  table: Table<TData>;
  handleFiltersUpdate: (columnFilters: Array<ColumnFilter>) => void;
}

export default function TableToolbar<T extends Record<string, unknown>>(
  props: Props<T>,
) {
  const { table, handleFiltersUpdate } = props;

  return (
    <div className="border-b-2 px-4 py-3">
      <div className="flex flex-col items-center gap-2 lg:flex-row">
        <div className="flex w-full flex-col items-center gap-3 lg:w-[80%] lg:flex-row">
          <TableSearchWithButton
            className={props.tableFilters ? 'lg:max-w-[55%]' : 'lg:max-w-[65%]'}
            update={(value: string) => table.setGlobalFilter(value)}
          />
          {props.tableFilters && (
            <props.tableFilters
              table={table}
              handleFiltersUpdate={(columnFilters: Array<ColumnFilter>) =>
                handleFiltersUpdate(columnFilters, table)
              }
            />
          )}
        </div>
        <TableDropdown table={table} />
      </div>
    </div>
  );
}
